// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxJOzlZwBbF43jtd38TR_CSkTxUDTjflU',
    appId: '1:46327534389:web:1481a1a0ae89ed924af27c',
    messagingSenderId: '46327534389',
    projectId: 'assignment-94108',
    authDomain: 'assignment-94108.firebaseapp.com',
    storageBucket: 'assignment-94108.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-TlpijHCKBH-s4wvTop1FqvvLiHUxJGc',
    appId: '1:46327534389:android:70e92c49c49b02754af27c',
    messagingSenderId: '46327534389',
    projectId: 'assignment-94108',
    storageBucket: 'assignment-94108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASghgF4bFEOOZKTwIlLgqRLyy4srGnccU',
    appId: '1:46327534389:ios:82422a98cee71bfd4af27c',
    messagingSenderId: '46327534389',
    projectId: 'assignment-94108',
    storageBucket: 'assignment-94108.appspot.com',
    iosBundleId: 'com.example.flutterfirebasecrudapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASghgF4bFEOOZKTwIlLgqRLyy4srGnccU',
    appId: '1:46327534389:ios:88872cc747e8e6944af27c',
    messagingSenderId: '46327534389',
    projectId: 'assignment-94108',
    storageBucket: 'assignment-94108.appspot.com',
    iosBundleId: 'com.example.flutterfirebasecrudapp.RunnerTests',
  );
}
